### ISSUE TITLE
How to view sheet

### ISSUE THREAD

**Issue by quickpots** [Derpseh/Spyglass#19]
What Is used to view sheets for Spyglass?

**Comment by Aptenodyte** [comment]
Any program that can view spreadsheets, such as Google Sheets or Excel.

**Comment by khronion** [comment]
Spyglass creates a spreadsheet in the same folder where you ran it from. You can find a guide to reading the spreadsheets here: https://github.com/Derpseh/Spyglass/blob/master/docs/interpreting_sheets.md
