### ISSUE TITLE
VERSION constant is 3.0.1 even in 3.0.2 and 3.0.3 tags

### ISSUE THREAD

**Issue by NotAName320** [Derpseh/Spyglass#46]
affects user agent and logging, the former making it somewhat problematic as it is giving wrong information to the NS server.

the release .exe of spyglass is logging 3.0.1 as well, suggesting that this wasn't fixed in builds.

**Comment by esfalsa** [comment]
Seems like this is an issue with (what's tagged/released as) 3.0.4 as well.

**Comment by the-lucilia** [comment]
Looks like line 21 of spyglass.py just needs to update the VERSION constant to the right version number.

cc: @AavHRF

**Comment by AavHRF** [comment]
Fixed.
